version: '3.9'
services:
  my_app:
    build: .
    image: uit-docker-app
    container_name: uit-docker-app
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: uit-mongo-db
    ports:
      - "27000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
